### ISSUE TITLE
json namespace not recognized

### ISSUE THREAD

**Issue by cappah** [ralampay/ann#8]
Within main.cpp, `auto configJson = json::parse(str);` shows error: 
E0304: no instance of overloaded function _"nlohmann::basic_json<ObjectType, ArrayType, BooleanType....
matches the argument list"_

**Comment by ralampay** [comment]
Hi

Maybe you did not include a json config file? How are you running the program?

**Comment by cappah** [comment]
I built the project with CMake (VS2017 x64). When I run the program I get an exception thrown at fstream line  267. The config.json.dist file is in the ann-master folder

**Comment by ralampay** [comment]
the .dist file is actually just a template. You should copy it to your own config.json file. I've pushed a new version of the .dist file and just change it to your needs. Let me know if you have questions about the parameters. I haven't created any documentation yet for what each parameter means.

**Comment by ralampay** [comment]
Closing this now. Might open an issue to make sure you pass the json file when running the program.
